Easy 1328
DANS-KNAW/easy-bag-store pull request #42
Opened 2017-11-06 08:50 UTC by alexal14

Fixes EASY-

#### When applied it will...
* 
* 
* 

#### Where should the reviewer @DANS-KNAW/easy start?

#### How should this be manually tested?

#### Related pull requests on github

repo                       | PR
-------------------------- | -----------------
easy-                      | [PR#](PRlink)

2017-11-06 09:41 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.bagstore/component/BagStoresComponent.scala
> +import scala.util.{Failure, Success, Try}
Applying the DANS code formatter would prevent this change.

2017-11-06 09:41 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.bagstore/component/BagStoreComponent.scala
> +                _ <- processor.complete(stagedBag)
please undo this chance

2017-11-06 10:32 UTC, jo-pol requested changes

2017-11-06 10:32 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.bagstore/component/BagStoresComponent.scala
> +    def getStream(itemId: ItemId, output: => OutputStream, fromStore: Option[Path] = None): Try[Unit] = {
The line above is the only difference with the `get` method. I don't understand the magic. Do you really need to return a Unit? At first sight I'd expect a stream.

2017-11-06 10:32 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.bagstore/server/BagsServletComponent.scala
> +              case "text/plain" | "*/*" | null => bagStores.enumFiles(bagId).map(files => Ok(files.toList.mkString("\n")))
An empty OK doesn't seem of much use to me, we'll need the stream or its content.

2017-11-06 10:32 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.easy.bagstore/server/BagsServletComponent.scala
> +            .map(_ => Ok())
again I would not expect an empty OK()

2017-11-07 09:12 UTC, PaulBoon commented on src/main/scala/nl.knaw.dans.easy.bagstore/server/BagsServletComponent.scala
>      get("/:uuid") {
We decided not to have zipping functionality for PDBS, so please get it out of this PR. We can do zipping later on, maybe even in another module.

2017-11-08 10:11 UTC, PaulBoon commented
I will clean things up and do another PR for this.

2017-11-09 10:10 UTC, lindareijnhoudt commented
this is part of
https://github.com/DANS-KNAW/easy-bag-store/pull/43
so i am closing this one

2017-11-09 10:10 UTC, closed without merging